name: polymorphism
description: "A Flutter Web portfolio showcasing the identity of an Ultimate Polymorphism — a visionary who balances engineering, art, and design."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  url_launcher: ^6.3.1
  meta: ^1.15.0
  google_fonts: ^6.2.1
  visibility_detector: ^0.4.0
  grain: ^0.0.1
  auto_size_text: ^3.0.0
  flutter_tilt: ^3.2.1
  stacked_card_carousel: ^0.0.4
  intl: ^0.19.0
  lucide_icons_flutter: ^3.0.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets: 
    - assets/images/
  uses-material-design: true